# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mixtape' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mixtape

  # RxSwift & RxCocoa
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # Rx Flow
  pod 'RxFlow'

  # Alamofire
  pod "Alamofire", "= 4.5.1"

  # Swift Lint
  pod 'SwiftLint'

  target 'MixtapeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MixtapeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
